In [8]:
import pandas as pd

df = pd.read_csv("../data/raw/all_games_1024.csv")

print(df.shape)
print(df.columns)
df.head()

(290826, 22)
Index(['thrower', 'thrower_x', 'thrower_y', 'receiver', 'receiver_x',
       'receiver_y', 'turnover', 'possession_num', 'possession_throw',
       'game_quarter', 'quarter_point', 'is_home_team', 'home_team_score',
       'away_team_score', 'gameID', 'total_points', 'home_teamID',
       'away_teamID', 'current_line', 'times', 'home_team_win', 'score_diff'],
      dtype='str')

,thrower,thrower_x,thrower_y,receiver,receiver_x,receiver_y,turnover,possession_num,possession_throw,game_quarter,...,home_team_score,away_team_score,gameID,total_points,home_teamID,away_teamID,current_line,times,home_team_win,score_diff
0,jnissen,1.02,15.14,jmalks,-8.17,23.51,0,1,1,1,...,0,0,2023-06-24-DC-BOS,0,glory,breeze,"['tmonroe', 'khealey', 'boort', 'mmcdonnel', '...",2880.000000,0,0
1,jmalks,-8.17,23.51,jnissen,2.18,27.08,0,1,2,1,...,0,0,2023-06-24-DC-BOS,0,glory,breeze,"['tmonroe', 'khealey', 'boort', 'mmcdonnel', '...",2876.578947,0,0
2,jnissen,2.18,27.08,jmalks,-10.21,33.56,0,1,3,1,...,0,0,2023-06-24-DC-BOS,0,glory,breeze,"['tmonroe', 'khealey', 'boort', 'mmcdonnel', '...",2873.157895,0,0
3,jmalks,-10.21,33.56,jnissen,-3.94,26.79,0,1,4,1,...,0,0,2023-06-24-DC-BOS,0,glory,breeze,"['tmonroe', 'khealey', 'boort', 'mmcdonnel', '...",2869.736842,0,0
4,jnissen,-3.94,26.79,boort,12.96,36.26,0,1,5,1,...,0,0,2023-06-24-DC-BOS,0,glory,breeze,"['tmonroe', 'khealey', 'boort', 'mmcdonnel', '...",2866.315789,0,0

In [9]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 290826 entries, 0 to 290825
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   thrower           290826 non-null  str
 1   thrower_x         290826 non-null  float64
 2   thrower_y         290826 non-null  float64
 3   receiver          273936 non-null  str
 4   receiver_x        290826 non-null  float64
 5   receiver_y        290826 non-null  float64
 6   turnover          290826 non-null  int64
 7   possession_num    290826 non-null  int64
 8   possession_throw  290826 non-null  int64
 9   game_quarter      290826 non-null  int64
 10  quarter_point     290826 non-null  int64
 11  is_home_team      290826 non-null  bool
 12  home_team_score   290826 non-null  int64
 13  away_team_score   290826 non-null  int64
 14  gameID            290826 non-null  str
 15  total_points      290826 non-null  int64
 16  home_teamID       290826 non-null  str
 17  away_teamID       290826 non-null  str
 18  current_line      290757 non-null  str
 19  times             290826 non-null  float64
 20  home_team_win     290826 non-null  int64
 21  score_diff        290826 non-null  int64
dtypes: bool(1), float64(5), int64(10), str(6)
memory usage: 46.9 MB

,thrower_x,thrower_y,receiver_x,receiver_y,turnover,possession_num,possession_throw,game_quarter,quarter_point,home_team_score,away_team_score,total_points,times,home_team_win,score_diff
count,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.0,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000,290826.000000
mean,0.395374,51.250743,0.458543,59.614521,0.068216,1.200897,5.818159,2.465034,0.0,10.004769,9.418360,19.423129,1458.822921,0.554868,0.586409
std,13.015376,23.307959,13.099142,26.217124,0.252117,0.524744,4.836279,1.124513,0.0,6.669758,6.337459,12.253395,837.180475,0.496981,4.376350
min,-26.670000,0.000000,-26.670000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,-297.000000,0.000000,-24.000000
25%,-9.830000,32.590000,-10.100000,38.450000,0.000000,1.000000,2.000000,1.000000,0.0,4.000000,4.000000,9.000000,738.142857,0.000000,-2.000000
50%,0.220000,49.630000,0.430000,57.220000,0.000000,1.000000,5.000000,2.000000,0.0,9.000000,9.000000,19.000000,1470.444444,1.000000,0.000000
75%,10.770000,70.090000,11.220000,79.220000,0.000000,1.000000,8.000000,3.000000,0.0,15.000000,14.000000,29.000000,2187.666667,1.000000,3.000000
max,26.660000,100.000000,26.660000,120.000000,1.000000,7.000000,63.000000,5.000000,0.0,34.000000,36.000000,57.000000,2880.000000,1.000000,21.000000

In [ ]:
from ufa import get_games_since_2024

games = get_games_since_2024()
games.head()

,gameID,awayTeamID,homeTeamID,awayScore,homeScore,status,startTimestamp,startTimezone,streamingURL,updateTimestamp,week,location
0,2024-04-26-MTL-BOS,royal,glory,17,19,Final,2024-04-26T19:00:00-04:00,EDT,https://www.watchufa.tv/videos/montreal-at-bos...,2024-06-22T22:36:54.753Z,week-1,Hormel Stadium
1,2024-04-26-DAL-HTX,legion,havoc,21,26,Final,2024-04-26T19:30:00-05:00,CDT,https://www.watchufa.tv/videos/dallas-at-houst...,2024-05-22T23:31:03.779Z,week-1,Sabercats Stadium
2,2024-04-27-SD-SEA,growlers,cascades,14,28,Final,2024-04-27T14:00:00-07:00,PDT,https://www.watchufa.tv/videos/san-diego-at-se...,2024-05-22T23:31:19.738Z,week-1,Seattle Memorial Stadium
3,2024-04-27-MTL-NY,royal,empire,16,18,Final,2024-04-27T17:00:00-04:00,EDT,https://www.watchufa.tv/videos/montreal-at-new...,2024-05-22T23:31:11.733Z,week-1,Joseph F. Fosina Field
4,2024-04-27-ATL-CAR,hustle,flyers,16,24,Final,2024-04-27T18:00:00-04:00,EDT,https://www.watchufa.tv/videos/atlanta-at-caro...,2024-07-03T20:14:40.764Z,week-1,Durham County Stadium

: